### ISSUE TITLE
Cypress not starting with "npm run test" (including FIX)

### ISSUE THREAD

**Issue by Tholho** [OpenClassrooms-Student-Center/exercices-js-P8#2]
I think the config file lacks the proper command as it only echo that it cannot find tests.

Solution for me : 
>npm install
... wait.
>npx cypress open

Setup : macOS Sonoma, M2 Air.

**Comment by haaslaura** [comment]
Same with Windows 10. Thank you!

**Comment by ghost** [comment]
fixed with update of package json file
